services:
  api-tests:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: playwright-api-tests

    command: npm run test:qa

    volumes:
      - ./playwright-report:/app/playwright-report
      - ./allure-results:/app/allure-results